//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ТРПО4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abiturient
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string grajdanstvo { get; set; }
        public Nullable<int> Dom { get; set; }
        public Nullable<int> Korpys { get; set; }
        public Nullable<int> Kvartira { get; set; }
        public string L_goti { get; set; }
        public Nullable<int> Invalidnost_ { get; set; }
        public string Participation_in_hostilities { get; set; }
        public string Mother { get; set; }
        public string Father { get; set; }
        public Nullable<int> Sredniy_ball { get; set; }
        public Nullable<System.DateTime> Data_zayavleniya { get; set; }
        public Nullable<int> Nomer_zayavleniya { get; set; }
        public Nullable<int> ID_Nationality { get; set; }
        public Nullable<int> ID_Shkola { get; set; }
        public Nullable<int> ID_Specialnost_ { get; set; }
        public Nullable<int> ID_Ylitsa { get; set; }
    
        public virtual Nationality Nationality { get; set; }
        public virtual Shkola Shkola { get; set; }
        public virtual Special_nost_ Special_nost_ { get; set; }
        public virtual Ylitsa Ylitsa { get; set; }
    }
}
