//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ТРПО4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nas_pynkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nas_pynkt()
        {
            this.Ylitsa = new HashSet<Ylitsa>();
        }
    
        public int ID { get; set; }
        public string Naimenovanie { get; set; }
        public string Vid_nas_pynkta { get; set; }
        public Nullable<int> ID_Oblast_ { get; set; }
    
        public virtual Oblast_ Oblast_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ylitsa> Ylitsa { get; set; }
    }
}
